version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    networks:
      - fe_network
    depends_on:
      - web
  web:
    build: 
      dockerfile: Dockerfile
      context: .
      tags:
        - "tyi/python-flask"
    ports:
      - 5000
    networks:
      - fe_network
      - app_network
      - backend_network
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health"]
      interval: 2s
      timeout: 5s
      start_period: 10s
      retries: 30
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 30

volumes:
  mydata:
  traefik-ssl-certs:
    driver: local

networks:
  fe_network:
  app_network:
    internal: true
  backend_network:
    internal: true