version: "3"
services:
  web:
    hostname: web
    build: 
      dockerfile: Dockerfile
      context: .
      tags:
        - "tyi/python-flask"
    ports:
      - "9010-9013:5000"
    deploy:
      replicas: 4
    networks:
      - app_network
      - backend_network
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health"]
      interval: 2s
      timeout: 5s
      start_period: 10s
      retries: 30
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 30

volumes:
  mydata:
  traefik-ssl-certs:
    driver: local

networks:
  app_network:
  backend_network:
    internal: true